<?php

// configuration
require("../includes/config.php");

// if form was submitted
if ($_SERVER["REQUEST_METHOD"] == "POST")
{
    if (empty($_POST["username"]))
    {
        apologize("Please enter a username");
        exit;
    }
    else if (empty($_POST["password"]))
    {
        apologize("Please enter a password");
        exit;
    }
    else if ($_POST["password"] != $_POST["confirmation"])
    {
        apologize("Your password and confirmation don't match!");
        exit;
    }
    // Temporarily disabled since we don't have the email running yet
    // TODO make sure we get this or something like it working.
    /*
    else if ($_POST["key"] != crypt($_POST["email"]))
    {
        apologize("You entered an invalid registration key!");
        exit;
    }
     */
    else
    {
      // connect to the db
      $cxn = open_db_browse() or die ("message");
      // crypt() is no longer acceptable
      //$hash = crypt($_POST["password"], SALT);
      $hash = password_hash($_POST["password"], PASSWORD_DEFAULT);
      // TODO the DB field password_webuser is not large enough to hold the
      // hash generated by password_hash(). This doc is broken until corrected
      // SOLUTION: create new column, pw_hash_webuser, to store the new hashes
      // while we're creating new columns, also create 'last_login' to store
      // the date of the last successful login by each user.
      $query = "INSERT INTO WebUsers VALUES (NULL, :name_webuser, :password_webuser, :name_mundane_webuser, :email_webuser, :id_person)";
      $values = array('name_webuser' => $_POST['username'], 'password_webuser' => $hash, 'name_mundane_webuser' => $_POST['mundaneName'], 'email_webuser' => $_POST['email'], 'id_person' => $_POST['personId']);
      $sth = $cxn->prepare($query, array(PDO::ATTR_CURSOR => PDO::CURSOR_FWDONLY));
      $sth->execute($values);
      try {
        $result = $sth->fetchAll() ; //or die ("Couldn't execute insert query");
        if (!$result) { 
          echo "\nPDOStatement::errorInfo():\n";
          $arr= $sth->errorInfo();
          print_r($arr);
        }
      } catch ( PDOException $e ) {
        throw new MyDatabaseException( $e->getMessage(), (int)$e->getCode());
      }

        if ($result === false)
        {
            apologize("Something went wrong with your registration. The username you entered may already be in use. Try a different username\n");
        }
        else
        {
          echo "<h1>Got past query</h1>"; 
          $query ="SELECT LAST_INSERT_ID() AS id";
          $sth = $cxn->prepare($query);
          $result = $sth->fetchAll() or die ("Couldn't execute user_id fetch query");
          $id = $result[0]["id"];
          // remember that user's now logged in by storing user's ID in session
          $_SESSION["id"] = $id;

            // redirect to main
            redirect("/");
        }
    }
}
else
{
    // else render form
    render("register_form.php", ["title" => "Register"]);
}

?>
